language: php

dist: trusty

matrix:
  include:
    - php: '5.6'
      env: DB=MYSQL RECIPE_VERSION=4.3.x-dev
    - php: '7.0'
      env: DB=MYSQL RECIPE_VERSION=4.3.x-dev
    - php: '7.1'
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev
    - php: '7.2'
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev COVERAGE=1
    - php: '7.3'
      env: DB=PGSQL RECIPE_VERSION=4.5.x-dev

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require silverstripe/recipe-cms:"$RECIPE_VERSION" --no-update
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.x-dev --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - "if [ \"$COVERAGE\" != \"1\" ]; then vendor/bin/phpunit tests; fi"
  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover ~/coverage.xml tests; fi"

after_success:
  - >
    test "$COVERAGE" = "1"
    && cd externalurlfield
    && wget https://scrutinizer-ci.com/ocular.phar
    && php ocular.phar code-coverage:upload -v --format=php-clover ~/coverage.xml
