language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 7.1
      env: DB=SQLITE CORE_RELEASE=4 COVERAGE=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=4

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - "if [ \"$COVERAGE\" != \"1\" ]; then vendor/bin/phpunit externalurlfield/tests; fi"
  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover ~/coverage.xml externalurlfield/tests; fi"

after_success:
  - >
    test "$COVERAGE" = "1"
    && wget https://scrutinizer-ci.com/ocular.phar
    && php ocular.phar code-coverage:upload -v --format=php-clover ~/coverage.xml
